#include <sokol/sokol_gfx.h>
#include <sokol/sokol_app.h>
#include <sokol/sokol_glue.h>
#include <sokol/sokol_log.h>
#include "triangle.h"          /* generated by gamelib_add_shader */

static sg_pipeline g_pip;
static sg_bindings g_bind;

static void init(void) {
  sg_setup(&(sg_desc){ .environment = sglue_environment(), .logger.func = slog_func });

  /* x, y, z, r, g, b, a */
  static const float vertices[] = {
     0.0f,  0.5f, 0.5f,  1.0f, 0.0f, 0.0f, 1.0f,
     0.5f, -0.5f, 0.5f,  0.0f, 1.0f, 0.0f, 1.0f,
    -0.5f, -0.5f, 0.5f,  0.0f, 0.0f, 1.0f, 1.0f,
  };
  g_bind.vertex_buffers[0] = sg_make_buffer(&(sg_buffer_desc){
      .data = SG_RANGE(vertices), .label = "triangle-vertices" });

  g_pip = sg_make_pipeline(&(sg_pipeline_desc){
      .shader = sg_make_shader(triangle_shader_desc(sg_query_backend())),
      .layout = { .attrs = {
          [ATTR_triangle_position].format = SG_VERTEXFORMAT_FLOAT3,
          [ATTR_triangle_color0].format   = SG_VERTEXFORMAT_FLOAT4 } },
      .label = "triangle-pipeline" });
}

static void frame(void) {
  sg_pass pass = { .action = { .colors[0] = { .load_action = SG_LOADACTION_CLEAR,
                                              .clear_value = { 0.1f, 0.1f, 0.12f, 1.0f } } },
                   .swapchain = sglue_swapchain() };
  sg_begin_pass(&pass);
  sg_apply_pipeline(g_pip);
  sg_apply_bindings(&g_bind);
  sg_draw(0, 3, 1);
  sg_end_pass();
  sg_commit();
}

static void cleanup(void) { sg_shutdown(); }

sapp_desc sokol_main(int argc, char *argv[]) {
  (void)argc; (void)argv;
  return (sapp_desc){ .init_cb = init, .frame_cb = frame, .cleanup_cb = cleanup,
                      .width = 640, .height = 480, .window_title = "gamelib shader",
                      .logger.func = slog_func };
}
