#!/usr/bin/env python3
"""Vendoring for game-lib. Python 3.11+, standard library only.

The manifest (tools/vendor.toml) is authoritative. Each entry owns exactly one
subtree, which this tool deletes and re-creates; it additionally rewrites the
manifest itself and each entry's VERSION and LICENSE, in place, never by
deleting a directory.

Networking happens in exactly two places: `update`, and `list --check-upstream`.
No build, configure or CI run ever calls them."""
import argparse, hashlib, re, shutil, subprocess, sys, tempfile, tomllib
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "tools" / "vendor.toml"
NOTICES = ROOT / "THIRD-PARTY-NOTICES.md"

def load():
    with MANIFEST.open("rb") as f:
        return tomllib.load(f)

def _no_traversal(rel: str, name: str, field: str) -> Path:
    """Reject a manifest path component that could escape ROOT: an absolute
    path silently discards everything to its left when joined with `/`
    (Path("/repo") / "/etc" is Path("/etc")), and `..` segments escape by
    walking back up -- neither is caught by a plain Path join."""
    p = Path(rel)
    if p.is_absolute() or ".." in p.parts:
        raise SystemExit(f"vendor.py: entry '{name}': unsafe {field} path {rel!r}")
    return p

def resolve_paths(name: str, entry: dict) -> tuple[Path, Path]:
    """Resolve an entry's root and subtree, confined under ROOT. cmd_update
    unconditionally shutil.rmtree()s the subtree this returns -- it must
    never be able to point outside the repository, whether through an
    absolute path or a `..` segment in a hand-edited manifest."""
    root = ROOT / _no_traversal(entry["root"], name, "root")
    subtree = root / _no_traversal(entry["subtree"], name, "subtree")
    base = ROOT.resolve()
    if not root.resolve().is_relative_to(base) or not subtree.resolve().is_relative_to(base):
        raise SystemExit(f"vendor.py: entry '{name}': root/subtree escapes the repository root")
    return root, subtree

def tree_sha256(path: Path, normalise_eol: bool = False) -> str:
    """SHA-256 over the subtree: every file's relative path and bytes, ordered by
    the relative POSIX path string. Detects accidental modification of an imported
    snapshot. It does not prove provenance, and does not help against someone
    changing content and hash together -- it is insurance, not a foundation.

    Order by that string, never by sorting Path objects. PureWindowsPath compares
    case-insensitively, so `sorted(rglob(...))` puts src/CMakeLists.txt before
    src/aabb.c on Linux (uppercase C sorts first in ASCII) and after it on
    Windows. That yields a different hash for identical bytes, and it bit exactly
    one entry -- box2d, the only vendored tree with a mixed-case filename among
    lowercase siblings -- which is a memorably confusing way to fail."""
    h = hashlib.sha256()
    for rel in sorted(p.relative_to(path).as_posix()
                      for p in path.rglob("*") if p.is_file()):
        h.update(rel.encode())
        h.update(b"\0")
        data = (path / rel).read_bytes()
        if normalise_eol:
            data = data.replace(b"\r\n", b"\n")
        h.update(data)
        h.update(b"\0")
    return h.hexdigest()

def read_version(root: Path) -> dict:
    f = root / "VERSION.txt"
    if not f.exists():
        return {}
    out = {}
    for line in f.read_text(encoding="utf-8").splitlines():
        if ":" in line and not line.startswith("#"):
            k, _, v = line.partition(":")
            out[k.strip()] = v.strip()
    return out

def write_version(root: Path, name: str, entry: dict, digest: str):
    rel = root.relative_to(ROOT).as_posix()
    (root / "VERSION.txt").write_text(
        f"# Generated by tools/vendor.py. Do not edit.\n"
        f"# Re-create with: python3 tools/vendor.py update {name}\n"
        f"name: {name}\n"
        f"url: {entry['url']}\n"
        f"commit: {entry['commit']}\n"
        f"release: {entry.get('release', '-')}\n"
        f"date: {date.today().isoformat()}\n"
        f"subtree: {rel}/{entry['subtree']}\n"
        f"tree_sha256: {digest}\n", encoding="utf-8")

def git(*args, cwd=None):
    return subprocess.run(["git", *args], cwd=cwd, check=True,
                          capture_output=True, text=True).stdout

def fetch(entry, dest: Path):
    """Shallow-fetch the pinned commit. Falls back to a full clone when the
    server refuses to serve an arbitrary SHA."""
    dest.mkdir(parents=True, exist_ok=True)
    git("init", "-q", cwd=dest)
    git("remote", "add", "origin", entry["url"], cwd=dest)
    try:
        git("fetch", "--depth", "1", "origin", entry["commit"], cwd=dest)
        git("checkout", "-q", "FETCH_HEAD", cwd=dest)
    except subprocess.CalledProcessError:
        shutil.rmtree(dest)
        git("clone", "-q", entry["url"], str(dest))
        git("checkout", "-q", entry["commit"], cwd=dest)

def copy_items(entry, src: Path, subtree: Path):
    for item in entry["copy"]:
        if isinstance(item, str):
            frm, to, is_tree = item, item, False
        else:
            frm, to, is_tree = item["from"], item["to"], item.get("tree", False)
        s = src / frm
        d = subtree / to
        if is_tree:
            shutil.copytree(s, d, dirs_exist_ok=True)
        else:
            d.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(s, d)

def cmd_update(args):
    data = load()
    entry = data[args.name]
    root, subtree = resolve_paths(args.name, entry)

    if args.commit:
        entry["commit"] = args.commit
        entry["release"] = "-"   # an explicit manual pin isn't known to match any tag
    elif args.recheck:
        entry["release"] = entry.get("release", "-")   # re-vendor the pin as-is
    else:
        entry["commit"], tag = resolve_latest(entry)
        entry["release"] = tag if tag else "-"

    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "src"
        fetch(entry, src)
        if subtree.exists():
            shutil.rmtree(subtree)          # the ONLY directory we delete
        subtree.mkdir(parents=True)
        copy_items(entry, src, subtree)
        shutil.copy2(src / entry["license"], root / "LICENSE")

    if entry.get("bundled"):
        got = fetch_bundled(entry)
        print(f"{args.name}: bundled licences: {', '.join(got)}")

    digest = tree_sha256(subtree)
    write_version(root, args.name, entry, digest)
    set_manifest_pin(args.name, entry["commit"],
                      entry["release"] if entry["release"] != "-" else None)
    n = sum(1 for p in subtree.rglob("*") if p.is_file())
    print(f"{args.name}: {entry['commit'][:12]}  {n} files  {digest[:12]}")
    return 0

def resolve_latest(entry):
    """Latest release tag if the project publishes releases, else default-branch
    HEAD. Preferring a tag keeps the pin on an audited revision. Returns
    (sha, tag), with tag None when the resolved revision carries no tag --
    callers must not keep a stale tag around in that case."""
    out = subprocess.run(["git", "ls-remote", "--tags", "--refs", entry["url"]],
                         capture_output=True, text=True, check=True).stdout
    tags = [(sha, ref.rsplit("/", 1)[-1])
            for sha, ref in (l.split("\t") for l in out.splitlines() if "\t" in l)]
    semver = [(sha, t) for sha, t in tags if re.fullmatch(r"v?\d+(\.\d+)*", t)]
    if semver:
        def key(item):
            return [int(x) for x in item[1].lstrip("v").split(".")]
        return max(semver, key=key)
    out = subprocess.run(["git", "ls-remote", entry["url"], "HEAD"],
                         capture_output=True, text=True, check=True).stdout
    return out.split()[0], None

def rewrite_pin(text: str, name: str, commit: str, release) -> str:
    """Rewrite one table's pinned commit -- including its trailing '# vX.Y.Z'
    comment, if any -- and keep its `release` key in sync with the tag
    actually resolved. `release` is None when the resolved revision carries
    no tag, which must clear any stale tag rather than leave it behind. If
    the table has no `release` key yet but a tag WAS resolved, one is
    inserted right after the commit line -- a no-argument `update` that
    lands on a tagged revision means the pin genuinely is that tag now, and
    `release: -` would misstate it, even for an entry that never tracked a
    release before. Pure text transform, no file I/O, so it can be exercised
    against a fixture."""
    lines = text.splitlines(keepends=True)
    start = end = None
    for i, line in enumerate(lines):
        if line.strip() == f"[{name}]":
            start = i
        elif start is not None and i > start and line.lstrip().startswith("["):
            end = i
            break
    if start is None:
        raise SystemExit(f"vendor.py: could not find table '[{name}]' in manifest")
    if end is None:
        end = len(lines)

    commit_i = release_i = None
    for i in range(start, end):
        stripped = lines[i].lstrip()
        if commit_i is None and stripped.startswith("commit"):
            commit_i = i
        elif release_i is None and stripped.startswith("release"):
            release_i = i
    if commit_i is None:
        raise SystemExit(f"vendor.py: could not find 'commit' in table '[{name}]'")

    comment = f"   # {release}" if release else ""
    lines[commit_i] = re.sub(r'"[0-9a-f]{40}"[ \t]*(#.*)?\s*$',
                              f'"{commit}"{comment}\n', lines[commit_i])
    if release_i is not None:
        lines[release_i] = re.sub(r'"[^"]*"', f'"{release if release else "-"}"',
                                  lines[release_i], count=1)
    elif release:
        # No existing `release` key, but a tag was resolved -- insert one
        # right after the (just-rewritten) commit line, inside this same
        # table. commit_i is still valid: nothing before it has shifted.
        lines.insert(commit_i + 1, f'release = "{release}"\n')
    return "".join(lines)

def set_manifest_pin(name: str, commit: str, release):
    """Rewrite the named table's commit (and, if tracked, release) in place.
    The manifest is the authoritative pin, so an update that changed only
    VERSION would leave `check` failing immediately."""
    MANIFEST.write_text(rewrite_pin(MANIFEST.read_text(encoding="utf-8"), name, commit, release),
                        encoding="utf-8")

def bundled_dir(entry) -> Path:
    return ROOT / entry["root"] / "third-party-licenses"

def fetch_bundled(entry) -> list[str]:
    """Fetch the licence text of each component statically linked into a
    vendored binary. Network; called only from `update`.

    A single file per repository, over HTTPS, rather than the shallow clone the
    main entries use -- cloning glslang to read one LICENSE.txt would pull ~79 MB
    for 11 kB of text."""
    import urllib.request
    out = bundled_dir(entry)
    out.mkdir(parents=True, exist_ok=True)
    names = []
    for b in entry.get("bundled", []):
        owner_repo = b["url"].removeprefix("https://github.com/").removesuffix(".git")
        sha = subprocess.run(["git", "ls-remote", b["url"], "HEAD"],
                             capture_output=True, text=True, check=True).stdout.split()[0]
        raw = f"https://raw.githubusercontent.com/{owner_repo}/{sha}/{b['path']}"
        with urllib.request.urlopen(raw) as r:
            text = r.read().decode("utf-8", "replace")
        dest = out / f"{b['name']}.txt"
        dest.write_text(
            f"Licence of {b['name']}, statically linked into the sokol-shdc\n"
            f"binaries in ../bin/. Fetched from {b['url']}\n"
            f"at {sha} ({b['path']}) on {date.today().isoformat()}.\n"
            f"\n"
            f"Upstream publishes no record of which revision built those binaries,\n"
            f"so this is the current text rather than the exact build's.\n"
            f"{'-' * 70}\n\n" + text, encoding="utf-8")
        names.append(b["name"])
    return names

def render_notices() -> str:
    """Build THIRD-PARTY-NOTICES.md from what is on disk. Offline."""
    data = load()
    parts = [
        "# Third-party notices",
        "",
        "game-lib redistributes the following. Its own code is MIT (see `LICENSE`);",
        "this file exists so that a consumer shipping a **binary** -- which carries no",
        "`libs/` tree -- can satisfy the notice requirements in one paste.",
        "",
        "Generated by `tools/vendor.py notices`. Do not edit.",
        "",
    ]
    for name, entry in data.items():
        lic = ROOT / entry["root"] / "LICENSE"
        parts += [f"## {name}", "", f"- Upstream: {entry['url']}",
                  f"- Pinned at: `{entry['commit']}`" +
                  (f" ({entry['release']})" if entry.get("release") else ""),
                  "", "```", lic.read_text(encoding="utf-8").rstrip(), "```", ""]
        for b in entry.get("bundled", []):
            f = bundled_dir(entry) / f"{b['name']}.txt"
            parts += [f"### {name}: bundled {b['name']}", "",
                      f"Statically linked into the {name} binaries.", "",
                      "```", f.read_text(encoding="utf-8").rstrip(), "```", ""]
    return "\n".join(parts) + "\n"

def cmd_notices(_args):
    NOTICES.write_text(render_notices(), encoding="utf-8")
    print(f"wrote {NOTICES.relative_to(ROOT)}")
    return 0

def cmd_check(_args):
    bad = []
    for name, entry in load().items():
        root, subtree = resolve_paths(name, entry)
        v = read_version(root)
        if not subtree.exists():
            bad.append(f"{name}: subtree missing ({subtree}); run: vendor.py update {name}")
            continue
        if v.get("commit") != entry["commit"]:
            bad.append(f"{name}: VERSION commit {v.get('commit')} != manifest {entry['commit']}")
        actual = tree_sha256(subtree)
        if v.get("tree_sha256") != actual:
            # Distinguish a real edit from a checkout whose line endings were
            # translated. Git for Windows converts LF to CRLF by default, which
            # changes every byte-exact hash here and produces a mismatch on all
            # entries at once -- a confusing way to learn that .gitattributes is
            # missing, so say it outright.
            if tree_sha256(subtree, normalise_eol=True) == v.get("tree_sha256"):
                bad.append(f"{name}: tree_sha256 mismatch, but the bytes match once "
                           f"CRLF is normalised to LF -- this checkout translated line "
                           f"endings. The repository needs '* -text' in .gitattributes; "
                           f"re-clone after adding it. The tree itself is unmodified.")
            else:
                bad.append(f"{name}: tree_sha256 mismatch -- the vendored tree was modified. "
                           f"Repair with: vendor.py update {name} --recheck")
        for b in entry.get("bundled", []):
            f = bundled_dir(entry) / f"{b['name']}.txt"
            if not f.exists():
                bad.append(f"{name}: bundled licence missing ({f.relative_to(ROOT)}); "
                           f"run: vendor.py update {name}")
    if not NOTICES.exists():
        bad.append("THIRD-PARTY-NOTICES.md missing; run: vendor.py notices")
    elif NOTICES.read_text(encoding="utf-8") != render_notices():
        bad.append("THIRD-PARTY-NOTICES.md is stale; regenerate: vendor.py notices")
    for b in bad:
        print(b, file=sys.stderr)
    return 1 if bad else 0

def cmd_list(args):
    for name, entry in load().items():
        v = read_version(ROOT / entry["root"])
        line = f"{name:<14} {entry['commit'][:12]}  {entry.get('release', '-'):<8} {v.get('date', '-')}"
        if args.check_upstream:
            latest, tag = resolve_latest(entry)
            behind = f"behind: {latest[:12]}" + (f" ({tag})" if tag else "")
            line += "  " + ("up to date" if latest == entry["commit"] else behind)
        print(line)
    return 0

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("list", help="show pinned versions (offline by default)")
    p.add_argument("--check-upstream", action="store_true",
                   help="contact each remote to report whether a pin is behind")
    p.set_defaults(fn=cmd_list)

    p = sub.add_parser("update", help="re-vendor one entry")
    p.add_argument("name")
    p.add_argument("--commit", help="move to this exact commit")
    p.add_argument("--recheck", action="store_true",
                   help="re-vendor the pinned commit without moving it")
    p.set_defaults(fn=cmd_update)

    p = sub.add_parser("check", help="verify every entry against the manifest")
    p.set_defaults(fn=cmd_check)

    p = sub.add_parser("notices", help="regenerate THIRD-PARTY-NOTICES.md (offline)")
    p.set_defaults(fn=cmd_notices)

    args = ap.parse_args()
    return args.fn(args)

if __name__ == "__main__":
    sys.exit(main())
