# Helpers shared by every libs/<name>/CMakeLists.txt. These do only the uniform
# parts -- target creation, the namespaced alias, the PUBLIC include root, and
# registration for the configure summary. Anything platform- or config-varying
# stays in the library's own CMakeLists, where a reader looks for it.

function(gamelib_add_library)
  cmake_parse_arguments(PARSE_ARGV 0 ARG "" "NAME;INCLUDE_ROOT" "SOURCES;PRIVATE_INCLUDES;LIBS")
  if(NOT ARG_NAME)
    message(FATAL_ERROR "gamelib_add_library: NAME is required")
  endif()
  if(NOT ARG_SOURCES)
    message(FATAL_ERROR "gamelib_add_library(${ARG_NAME}): SOURCES is required")
  endif()
  if(NOT ARG_INCLUDE_ROOT)
    set(ARG_INCLUDE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()

  set(tgt gamelib_${ARG_NAME})
  add_library(${tgt} STATIC ${ARG_SOURCES})
  add_library(gamelib::${ARG_NAME} ALIAS ${tgt})
  target_include_directories(${tgt} PUBLIC "${ARG_INCLUDE_ROOT}")
  if(ARG_PRIVATE_INCLUDES)
    target_include_directories(${tgt} PRIVATE ${ARG_PRIVATE_INCLUDES})
  endif()
  if(ARG_LIBS)
    target_link_libraries(${tgt} PUBLIC ${ARG_LIBS})
  endif()
  # A consumer building a shared library needs PIC in the static libs it links.
  set_target_properties(${tgt} PROPERTIES POSITION_INDEPENDENT_CODE ON)
  set_property(GLOBAL APPEND PROPERTY GAMELIB_DECLARED_TARGETS ${ARG_NAME})
endfunction()

function(gamelib_add_interface_library)
  cmake_parse_arguments(PARSE_ARGV 0 ARG "" "NAME;INCLUDE_ROOT" "FEATURES;LIBS")
  if(NOT ARG_NAME)
    message(FATAL_ERROR "gamelib_add_interface_library: NAME is required")
  endif()
  if(NOT ARG_INCLUDE_ROOT)
    set(ARG_INCLUDE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()

  set(tgt gamelib_${ARG_NAME})
  add_library(${tgt} INTERFACE)
  add_library(gamelib::${ARG_NAME} ALIAS ${tgt})
  target_include_directories(${tgt} INTERFACE "${ARG_INCLUDE_ROOT}")
  if(ARG_FEATURES)
    target_compile_features(${tgt} INTERFACE ${ARG_FEATURES})
  endif()
  if(ARG_LIBS)
    target_link_libraries(${tgt} INTERFACE ${ARG_LIBS})
  endif()
  set_property(GLOBAL APPEND PROPERTY GAMELIB_DECLARED_TARGETS ${ARG_NAME})
endfunction()

function(gamelib_add_header_library)
  cmake_parse_arguments(PARSE_ARGV 0 ARG "" "NAME;HEADER;IMPL_DEFINE;LANGUAGE" "LIBS")
  if(NOT ARG_NAME OR NOT ARG_HEADER OR NOT ARG_IMPL_DEFINE)
    message(FATAL_ERROR "gamelib_add_header_library: NAME, HEADER and IMPL_DEFINE are required")
  endif()
  if(NOT ARG_LANGUAGE)
    set(ARG_LANGUAGE C)
  endif()

  if(ARG_LANGUAGE STREQUAL "CXX")
    set(gen "${CMAKE_CURRENT_BINARY_DIR}/gamelib_${ARG_NAME}_impl.cc")
  else()
    set(gen "${CMAKE_CURRENT_BINARY_DIR}/gamelib_${ARG_NAME}_impl.c")
  endif()
  set(GAMELIB_IMPL_DEFINE ${ARG_IMPL_DEFINE})
  set(GAMELIB_IMPL_HEADER ${ARG_HEADER})
  configure_file("${GAMELIB_CMAKE_DIR}/single_header_impl.c.in" "${gen}" @ONLY)

  gamelib_add_library(NAME ${ARG_NAME} SOURCES "${gen}" LIBS ${ARG_LIBS})
endfunction()


# True when every named gamelib target has been declared. Examples use this so
# that a disabled library silently removes its example rather than erroring.
function(gamelib_have_targets out)
  foreach(n IN LISTS ARGN)
    if(NOT TARGET gamelib_${n})
      set(${out} FALSE PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out} TRUE PARENT_SCOPE)
endfunction()
